import { useEffect, useState } from 'react';
import { getExpansion } from '../api/expansion';
import { useBusiness } from '../context/useBusiness';

export default function ExpansionPage() {
  const { profile, config } = useBusiness();
  const [analysis, setAnalysis] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => { getExpansion(profile?.businessType || 'distributor').then((response) => setAnalysis(response.data)).catch(() => setError('Expansion intelligence is unavailable right now.')); }, [profile?.businessType]);
  if (error) return <div className="rounded-xl border border-amber-200 bg-amber-50 p-6 text-amber-800">{error}</div>;
  if (!analysis) return <div className="p-6 text-slate-600">Loading expansion intelligence...</div>;
  return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-blue-700">Expansion intelligence</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Where could {config.label.toLowerCase()} expand?</h1><p className="mt-2 text-slate-600">Synthetic demo evidence is clearly marked. Scores describe potential, not certainty.</p></div>{analysis.synthetic && <p className="rounded-lg bg-slate-200 px-3 py-2 text-sm text-slate-700">Synthetic demo data: connect operational data to replace these candidate signals.</p>}<div className="grid gap-5 lg:grid-cols-2">{analysis.candidates.map((candidate) => <article key={candidate.name} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Expansion opportunity</p><h2 className="mt-1 text-2xl font-bold text-slate-900">{candidate.name}</h2></div><span className="rounded-full bg-blue-100 px-3 py-1 text-sm font-semibold text-blue-700">{candidate.category}</span></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm">{[['Demand potential', candidate.demand], ['Customer density', candidate.customer_density], ['Coverage gap', candidate.coverage_gap], ['Competition', candidate.competition]].map(([label, value]) => <div key={label} className="rounded-lg bg-slate-50 p-3"><span className="block text-slate-500">{label}</span><strong className="mt-1 block text-slate-900">{typeof value === 'number' ? `${value}/100` : value}</strong></div>)}</div><div className="mt-5 border-t border-slate-100 pt-4"><p className="text-sm font-semibold text-slate-800">Why this location</p><p className="mt-1 text-sm text-slate-600">Strong business-specific demand with a meaningful current coverage gap.</p><p className="mt-4 text-sm font-semibold text-slate-800">Historical memory</p><p className="mt-1 text-sm text-slate-600">{candidate.historical_evidence}</p></div></article>)}</div></div>;
}